### ISSUE TITLE
权限和路径报错

### ISSUE THREAD

**Issue by Sundyfuther** [litten/hexo-theme-yilia#148]
chenxiaojia:~ lanou$ cd desktop
chenxiaojia:desktop lanou$ cd My-blog
chenxiaojia:My-blog lanou$ git clone git@github.com:litten/hexo-theme-yilia.git
Cloning into 'hexo-theme-yilia'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by MOxFIVE** [comment]
删除 Hexo 根目录下的 `db.json` 文件后再尝试。

**Comment by MOxFIVE** [comment]
先关闭 Git 窗口，然后删除 Hexo 根目录下的 `db.json` 文件，之后再尝试。

**Comment by Sundyfuther** [comment]
感谢亲，已解决！很高兴能得到你的指导和帮助！

Date: Wed, 25 Nov 2015 07:33:17 -0800

**Comment by Sundyfuther** [comment]
亲：     不好意思，又来打扰您了，因为太喜欢您的主题了，我也一直在想办法做一些我自己喜欢的优化，可是我发现我的能力非常有限， 根本做不了什么，所以想问问有没有关于您的主题的相关功能介绍，尽可能详细一些，比如我怎样才能把我的主页做成不被文章高 度撑开主页高度啊？怎样才能把home里的四个板块儿拿出来啊？怎样加一个留言板啊？怎样能把访客记录的博客链接留下啊？  如果我有这个能力我一定会自己去做的，可是，我只是学了一个月html css  js-ecma 的小白，看看您的原生让我感觉甚有压力，并且 感觉自己更有力量学习了。
 可是由于我天天用我的博客记笔记和自己的一些想法，每次想看自己的东西都要翻翻翻到最下面，这样的用户体验真的是不太好！我想 去我空间的博友们也不会多喜欢，但是犹豫您的结构相当的高端大气上档次，我又非常不想换！所以您能帮忙解决一下吗？
 收到请回复一下！

From: cxj8976@hotmail.com
To: reply@reply.github.com
Subject: RE: [hexo-theme-yilia] 权限和路径报错 (#148)
Date: Thu, 26 Nov 2015 07:03:18 +0000




感谢亲，已解决！很高兴能得到你的指导和帮助！

Date: Wed, 25 Nov 2015 07:33:17 -0800

**Comment by korvin101** [comment]
1. 比如我怎样才能把我的主页做成不被文章高 度撑开主页高度啊？

  在文章里加入来分隔摘要

2. 怎样加一个留言板啊？

  执行
  ```
  hexo new page
  ```
  在`/themes/yilia/_config.yml`的`menu`下加入
  ```
  # Header
  menu:
    主页: /
    所有文章: /archives
    # 随笔: /tags/随笔
    留言板: /guestbook
  ```

**Comment by Sundyfuther** [comment]
亲：按照您的指示，报以下错误








ERROR Theme config load failed.
ERROR Process failed: _config.ymlDate: Fri, 27 Nov 2015 07:08:41 -0800

**Comment by korvin101** [comment]
这是完整的报错信息？

**Comment by Sundyfuther** [comment]
报错的只有这两行，其余的都是好的

Date: Fri, 27 Nov 2015 23:30:45 -0800

**Comment by korvin101** [comment]
@Sundyfuther 你检查下你改的主题配置文件，肯定是里面配置格式有错，像冒号后面要有一个空格

**Comment by korvin101** [comment]
@Sundyfuther 你把配置文件发我看下

**Comment by Sundyfuther** [comment]
好的，我晚上发给你，现在我们在上课，等下午下课吧，谢啦

Date: Fri, 27 Nov 2015 23:37:26 -0800

**Comment by korvin101** [comment]
:ok_hand:

Sundyfuther <notifications@github.com>于2015年11月28日周六 下午3:43写道：

**Comment by Sundyfuther** [comment]
我通过我的163邮箱发送给您了一个文件压缩包，犹豫不知道配置文件是什么，所以我就把整个blog文件夹压缩了给你，希望你不要介意，我对我用的东西还是有那么一
点点强迫症，所以很感谢您的帮忙，像我现在这种小白着实看不懂您这种神级代码，还望您一步帮我配置好了！

  
  



我现在迫切想解决的问题就是
1、把home里面的四个东西菜单，标签，友情链接和关于我拿出来跟主页和所有文章放在一起
2、怎样放一张图片做头像（最好是加勒比海盗Jack Sparrow的头像）
3、怎样加一个留言板啊？
4、怎样能把访客记录的博客链接留下啊？
原谅小白的无知，请帮一下忙，不胜感激！最后两个如果特别麻烦的话可以不做的！
ps:我的七牛账号cxj8976@hotmail.com   密码8976123xyz

**Comment by korvin101** [comment]
没有收到你的压缩包

Sundyfuther <notifications@github.com>于2015年11月28日周六 下午4:30写道：

**Comment by korvin101** [comment]
我的邮箱korvin101@gmail.com

变形刚金 <korvin101@gmail.com>于2015年11月28日周六 下午4:32写道：

**Comment by korvin101** [comment]
声明下，我不是主题作者。

变形刚金 <korvin101@gmail.com>于2015年11月28日周六 下午4:33写道：

**Comment by Sundyfuther** [comment]
我发送至您 notifications@github.com 的邮箱里了，您没收到吗？

**Comment by Sundyfuther** [comment]
这个没关系的，是不是作者有什么关系，您能帮我，我已经很感激了！谢谢您！
Date: Sat, 28 Nov 2015 00:35:14 -0800

**Comment by korvin101** [comment]
这是主题配置文件
`\My-blog\themes\hexo-theme-yilia\_config.yml`

报错问题就是之前我和你说的空格问题，配置文件`_config.yml`里冒号后面是要加空格的
你`留言版:`后面没加空格



1. 这4个不是独立页面，不好拿出来；
2. 头像文件放到博客根目录的`/source/images/`下（没有就新建），主题配置文件里写

  ```
  #你的头像url
  avatar: images/cxj.jpg
  ```
3. 按照最开始我和你说的就可以了，注意空格问题；
4. 配置多说评论，如果另人的多说关联了自己的博客，在你这里留言后会自动带上博客链接；

**Comment by korvin101** [comment]
`\My-blog\themes\hexo-theme-yilia\_config.yml`这里面配置大部分都有说明，请仔细看注释

**Comment by Sundyfuther** [comment]
好的好的，，，感谢您了！我先弄弄看…………hand

Date: Sat, 28 Nov 2015 01:05:50 -0800

**Comment by AFeng521web** [comment]
您好，非常喜欢这个主题，昨天配置好了，今天下了个content.json文件就用不了了，这是怎么回事，求大佬。YAMLException: duplicated mapping key at line 68, column 1:
    open_in_new: true
    ^
    at generateError (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at storeMappingPair (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:308:7)
    at readBlockMapping (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1071:9)
    at composeNode (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (G:\Blog\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (G:\Blog\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (G:\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (G:\Blog\blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (G:\Blog\blog\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (G:\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\Blog\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (G:\Blog\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (G:\Blog\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (G:\Blog\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
