### ISSUE TITLE
generate的时候，提示一长串“错误”？

### ISSUE THREAD

**Issue by zmhan** [litten/hexo-theme-yilia#152]
Unhandled rejection TypeError: /Users/id/Documents/Blog/themes/yilia/layout/page.ejs:1
   
 1|       <%- partial('_partial/article', {post: page, index: false})  %>
 
/Users/id/Documents/Blog/themes/yilia/layout/_partial/article.ejs:17

    15|       <% if (!index){ %>
    16|       <div class="article-info article-info-post">
    17|         <%- partial('post/tag') %>
    18|         <%- partial('post/category') %>
    19|         <div class="clearfix"></div>
    20|       </div>

/Users/id/Documents/Blog/themes/yilia/layout/_partial/post/tag.ejs:3
   
    1|   <% if (post.tags && post.tags.length){ %>
    2| 	<div class="article-tag tagcloud">
    3| 		<%- list_tags(post.tags, {
    4| 		    show_count: false,
    5| 		    class: 'article-tag'
    6| 		  }) %>

tags.sort is not a function
    at Object.listTagsHelper (/Users/id/Documents/Blog/node_modules/hexo/lib/plugins/helper/list_tags.js:24:15)   
    at eval (eval at <anonymous> (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:145)
    at eval (eval at <anonymous> (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:33:64)
    at /Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/id/Documents/Blog/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Render.renderSync (/Users/id/Documents/Blog/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/Users/id/Documents/Blog/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/Users/id/Documents/Blog/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1013)
    at eval (eval at <anonymous> (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:34:1044)
    at /Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/id/Documents/Blog/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Render.renderSync (/Users/id/Documents/Blog/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/Users/id/Documents/Blog/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/Users/id/Documents/Blog/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:101)
    at /Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/id/Documents/Blog/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/id/Documents/Blog/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/Users/id/Documents/Blog/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/id/Documents/Blog/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/id/Documents/Blog/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/id/Documents/Blog/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/id/Documents/Blog/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/id/Documents/Blog/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/id/Documents/Blog/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/id/Documents/Blog/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/id/Documents/Blog/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/id/Documents/Blog/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by 9662** [comment]
Are you defining any tags in the front matter for a non-post layout?

From [the docs](https://hexo.io/docs/front-matter.html#Categories-amp-Tags):
> Only posts support the use of categories and tags.
