### ISSUE TITLE
YAMLException

### ISSUE THREAD

**Issue by drduan** [litten/hexo-theme-yilia#161]
```ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: end of the stream or a document separator is expected at line 6, column 1:
    subnav:
    ^
    at generateError (/hexo/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
    at throwError (/hexo/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
    at readDocument (/hexo/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1500:5)
    at loadDocuments (/hexo/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1536:5)
    at Object.load (/hexo/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1553:19)
    at Hexo.yamlHelper (/hexo/blog/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /hexo/blog/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/hexo/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler 
、、、
<img width="570" alt="2016-01-02 11 55 23" src="https://cloud.githubusercontent.com/assets/7875572/12073159/0afce2d0-b148-11e5-913e-60a406770b3d.png">

    at process._tickCallback (node.js:442:13)
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
```

**Comment by drduan** [comment]
这个怎么解决啊

**Comment by mindthink** [comment]
缺少分隔符，一般都是因为缺少空格

**Comment by mindthink** [comment]
缺少分隔符，一般都是因为缺少空格

**Comment by Azha3** [comment]
你的yml格式有错，可以到这里面去检查你得yml是否有错
https://hexo.io/zh-cn/docs/configuration.html

**Comment by Azha3** [comment]
你的yml格式有错，可以到这里面去检查你得yml是否有错
