### ISSUE TITLE
关于开启搜索时报错的解决方法

### ISSUE THREAD

**Issue by BlackHole1** [litten/hexo-theme-yilia#360]
开启搜索时，需要运行`npm i hexo-generator-json-content --save`命令，但是启动的时候会报错：
```
ERROR Plugin load failed: hexo-generator-json-content
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Object.exports.runInThisContext (vm.js:53:16)
    at /home/black-hole/Black-hole/github/blog/node_modules/hexo/lib/hexo/index.js:227:17
    at tryCatcher (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/promise.js:628:18)
    at /home/black-hole/Black-hole/github/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/black-hole/Black-hole/github/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

需要你在根目录(非yilia目录)下进入`node_modules/hexo-generator-json-content`目录下，把里面的index.js文件的第一行加入:
`"use strict";`
即可成功。

link:<http://stackoverflow.com/questions/33001246/uncaught-syntaxerror-block-scoped-declarations-let-const-function-class-no>

**Comment by Froyo91** [comment]
通过您的方式解决了问题，十分感谢！

**Comment by litten** [comment]
其实是node版本太低，不支持ES的特性导致。
这样解决也行，但不推荐，最好是能把node升级到6.2以上版本。

**Comment by akeliw** [comment]
@BlackHole1 出现过此问题,win系统不能用n模块管理node版本,在nodejs官网下最新版exe文件替换node.exe即可

**Comment by JohnTian** [comment]
@BlackHole1 It works for me. Thanks a lot.
