### ISSUE TITLE
添加archive页面时编辑archive/index.md添加layout:archive后archive.ejs文件报错

### ISSUE THREAD

**Issue by irrun** [litten/hexo-theme-yilia#603]
Unhandled rejection TypeError: /Users/raina/Projects/myblog/themes/yilia/layout/archive.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: config.archive, index: true}) %>

/Users/raina/Projects/myblog/themes/yilia/layout/_partial/archive.ejs:15
    13| <% } else { %>
    14|   <% var last; %>
 >> 15|   <% page.posts.each(function(post, i){ %>
    16|     <% var year = post.date.year(); %>
    17|     <% if (last != year){ %>
    18|       <% if (last != null){ %>

Cannot read property 'each' of undefined
    at eval (eval at compile (/Users/raina/Projects/myblog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:40:18)
    at returnedFn (/Users/raina/Projects/myblog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/Users/raina/Projects/myblog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/raina/Projects/myblog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/raina/Projects/myblog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/raina/Projects/myblog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/Users/raina/Projects/myblog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:9:17)
    at returnedFn (/Users/raina/Projects/myblog/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/Users/raina/Projects/myblog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/raina/Projects/myblog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/raina/Projects/myblog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/Users/raina/Projects/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/raina/Projects/myblog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/raina/Projects/myblog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by irrun** [comment]
google了很久没有解决，求作者支招！

**Comment by irrun** [comment]
啊呀 解决了 忽略我。。

**Comment by VegaBai** [comment]
我终于找到了问题原因。。
1. 楼主的原因应该是特殊字符吧？反正我发现文章标题不能有冒号，似乎也不能有‘&’这种字符做tag，引起了后面代码的问题。。
2. 还有一个也很挫的原因是我把caregories和tags用法搞混了，如果在左边一栏主菜单添加项目的话，应该是categories而不是tags。。。

**Comment by YINChengfeng** [comment]
能问一下怎么解决的吗？试了好多方法了都不行
