### ISSUE TITLE
想试下开发步骤，报错了

### ISSUE THREAD

**Issue by LukaMod** [litten/hexo-theme-yilia#751]
开发环境都安装更新到最新了，`source-src`下的文件没动过。
<img width="1063" alt="screen shot 2018-04-23 at 1 20 45 am" src="https://user-images.githubusercontent.com/13666451/39097879-eacd9be6-4694-11e8-9396-79a0a3e575de.png">

**Comment by pangjunpeng** [comment]
提示的不很明显么，`webpack`没找到，`npm i webpack -g`

**Comment by saranfeishuang** [comment]
请问解决了吗？

**Comment by LukaMod** [comment]
@saranfeishuang 根目录安装依赖那步没做吧，当时好像是以为webpack装了可以跳过那步了，忘记了。后来没去折腾了，我原来只是想试着换个代码高亮风格的(￣ε(#￣)☆╰╮(￣▽￣///)

**Comment by saranfeishuang** [comment]
@LukaMod 您好，请问是安装什么依赖啊，是把webpack装到根目录吗？

**Comment by LukaMod** [comment]
@saranfeishuang `npm install` 那步吧，跟着开发步骤做下来试试看好了

**Comment by saranfeishuang** [comment]
@LukaMod 我全局安装了webpack，使用npm run dev，调用全局的webpack，发现无法使用webpack

  $ webpack
D:\blog\themes\yilia\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\blog\themes\yilia\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\blog\themes\yilia\node_modules\extract-text-webpack-plugin\ExtractedModule.js:30:42)
    at Module._compile (D:\blog\themes\yilia\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\blog\themes\yilia\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\blog\themes\yilia\node_modules\extract-text-webpack-plugin\index.js:7:23)
    at Module._compile (D:\blog\themes\yilia\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\blog\themes\yilia\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\blog\themes\yilia\webpack.config.js:3:25)
    at Module._compile (D:\blog\themes\yilia\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\blog\themes\yilia\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (D:\blog\themes\yilia\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (D:\blog\themes\yilia\node_modules\webpack-cli\bin\convert-argv.js:135:6)
