### ISSUE TITLE
请问出现这个错误是为什么 Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by wsh3776** [litten/hexo-theme-yilia#838]
$ hexo g -d
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable' of undefined
    at Hexo.logic (E:\@shwei\CS\hexo\blog\node_modules\hexo-auto-category\lib\logic.js:16:35)
    at Hexo.tryCatcher (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (E:\@shwei\CS\hexo\blog\node_modules\hexo\lib\extend\filter.js:60:50)
    at tryCatcher (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\@shwei\CS\hexo\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by colorfulsweet** [comment]
应该是有些配置项没写全导致静态化渲染出错了
ejs模板文件里面的 theme.xxx  就表示获取的是主题目录下的_config.yml内容
config.xxx 就表示获取根目录下的_config.yml内容

**Comment by Sissill** [comment]
我和你出现的问题几乎一样，不知道配置文件哪里写错了
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable' of undefined
    at D:\REPOs\hexo\themes\next-reloaded\scripts\filters\comment\gitalk.js:10:21
    at Filter.execSync (D:\REPOs\hexo\node_modules\hexo\lib\extend\filter.js:76:30)
    at Hexo.execFilterSync (D:\REPOs\hexo\node_modules\hexo\lib\hexo\index.js:470:31)
    at module.exports (D:\REPOs\hexo\themes\next-reloaded\scripts\events\lib\injects.js:58:8)
    at Hexo.<anonymous> (D:\REPOs\hexo\themes\next-reloaded\scripts\events\index.js:9:27)
    at Hexo.emit (events.js:333:22)
    at Hexo._generate (D:\REPOs\hexo\node_modules\hexo\lib\hexo\index.js:437:10)
    at D:\REPOs\hexo\node_modules\hexo\lib\hexo\index.js:310:24
    at tryCatcher (D:\REPOs\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (D:\REPOs\hexo\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (D:\REPOs\hexo\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\REPOs\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\REPOs\hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\REPOs\hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\REPOs\hexo\node_modules\bluebird\js\release\async.js:102:5)

从next主题v5.x升级到v6.x

**Comment by wudan3551** [comment]
我把主题的配置文件挪到 source/data/next.yml 里面之后就好了，参考 https://theme-next.org/docs/getting-started/data-files  里面的NextWay

**Comment by nanyancc** [comment]
我也有这个问题，我把我的博客源文件发到了TravisCi之后进行部署，就出错了。我使用matery主题。

$ hexo generate
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable' of undefined
    at Hexo.logic (/home/travis/build/HenryHe613/source/node_modules/hexo-abbrlink/lib/logic.js:59:44)
    at Hexo.tryCatcher (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/method.js:15:34)
    at /home/travis/build/HenryHe613/source/node_modules/hexo/lib/extend/filter.js:62:52
    at tryCatcher (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/HenryHe613/source/node_modules/bluebird/js/release/async.js:15:14)
INFO  hexo-blog-encrypt: encrypting "Yellow Pages" based on the password configured in Front-matter.
INFO  hexo-blog-encrypt: encrypting "梯子" based on the password configured in Front-matter.

**Comment by EarendelH** [comment]
在_config.yml 下添加
```
leancloud_counter:  #其他插件应该也是
    enable: true
```
我这么做解决了，可以试试
